require("dotenv").config();

const env = {
  URL: process.env.URL,
  DICOM_PROXY_URL: process.env.DICOM_PROXY_URL,

  // Local Base Path
  LOCAL_BASE_PATH: process.env.LOCAL_BASE_PATH,

  // Image Version
  RIS_IMAGE_VERSION: process.env.RIS_IMAGE_VERSION,
  RIS_V1_IMAGE_VERSION: process.env.RIS_V1_IMAGE_VERSION,
  BLUE_HALO_IMAGE_VERSION: process.env.BLUE_HALO_IMAGE_VERSION,
  OHIF_IMAGE_VERSION: process.env.OHIF_IMAGE_VERSION,
  ELVASOFT_DICOM_PROXY_IMAGE_VERSION:
    process.env.ELVASOFT_DICOM_PROXY_IMAGE_VERSION,

  // Yaml Files
  RIS_YAML_FILE: process.env.RIS_YAML_FILE,
  RIS_YAML_TEMPLATE_FILE: process.env.RIS_YAML_TEMPLATE_FILE || "ris.yaml.template",
  RIS_V1_YAML_FILE: process.env.RIS_V1_YAML_FILE,
  BLUE_HALO_YAML_FILE: process.env.BLUE_HALO_YAML_FILE,
  OHIF_YAML_FILE: process.env.OHIF_YAML_FILE,
  ELVASOFT_DICOM_PROXY_YAML_FILE:
    process.env.ELVASOFT_DICOM_PROXY_YAML_FILE ||
    "13-elvasoft-dicom-proxy.yaml",
  DCM4CHEE_YAML_FILE: process.env.DCM4CHEE_YAML_FILE,
  DCM4CHEE_POSTGRES_HOST:
    process.env.DCM4CHEE_POSTGRES_HOST || "visionx-supabase-db.supabase",

  // Supabase / PostgreSQL
  SUPABASE_HOST: process.env.SUPABASE_HOST,
  SUPABASE_PORT: parseInt(process.env.SUPABASE_PORT, 10) || 5432,
  SUPABASE_DATABASE: process.env.SUPABASE_DATABASE,
  SUPABASE_USER: process.env.SUPABASE_USER,
  SUPABASE_PASSWORD: process.env.SUPABASE_PASSWORD,
  SUPABASE_URL: process.env.SUPABASE_URL,
  SUPABASE_KEY: process.env.SUPABASE_KEY,

  // Mirth
  MIRTH_HOST: process.env.MIRTH_HOST,
  MIRTH_PORT: process.env.MIRTH_PORT,
  MIRTH_USERNAME: process.env.MIRTH_USERNAME,
  MIRTH_PASSWORD: process.env.MIRTH_PASSWORD,

  // Mirth Endpoint URLs (from env)
  KEYCLOAK_LOGIN: process.env.KEYCLOAK_LOGIN,
  CHECK_MWL_EXIST: process.env.CHECK_MWL_EXIST,
  CHECK_PATIENT_EXIST: process.env.CHECK_PATIENT_EXIST,
  PATIENT_HTTP_SENDER: process.env.PATIENT_HTTP_SENDER,
  CHANGESTATUS_MWL: process.env.CHANGESTATUS_MWL,
  CHECK_SERVICE_REQUEST_EXIST: process.env.CHECK_SERVICE_REQUEST_EXIST,
  CHECK_STUDY_EXIST_IN_FHIR: process.env.CHECK_STUDY_EXIST_IN_FHIR,
  PATCH_END_EXAM_SUPABASE: process.env.PATCH_END_EXAM_SUPABASE,
  GET_STUDY_MODALITY: process.env.GET_STUDY_MODALITY,
  IMAGINGSTUDY_HTTP_SENDER: process.env.IMAGINGSTUDY_HTTP_SENDER,
  SERVICE_REQUEST_HTTP_SENDER: process.env.SERVICE_REQUEST_HTTP_SENDER,
  PROCEDURE_HTTP_SENDER: process.env.PROCEDURE_HTTP_SENDER,
  SEND_AUDIT_LOG: process.env.SEND_AUDIT_LOG,
  SEND_AUDIT_TRAIL: process.env.SEND_AUDIT_TRAIL,
  KC_TOKEN_URL: process.env.KC_TOKEN_URL,
  KC_CLIENT_ID: process.env.KC_CLIENT_ID,
  KC_CLIENT_SECRET: process.env.KC_CLIENT_SECRET,
  KC_PASSWORD: process.env.KC_PASSWORD,
  KC_USERNAME: process.env.KC_USERNAME,
  FHIR_BASE: process.env.FHIR_BASE,
  // ... (add all others)
};

module.exports = env;
